repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: mixed-line-ending
    -   id: trailing-whitespace
    -   id: pretty-format-json
        args: [--autofix]
