# SPDX-FileCopyrightText: 2021-2022 Samuel Wu
#
# SPDX-License-Identifier: CC0-1.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: pretty-format-json
        args: [--autofix]
  - repo: https://github.com/fsfe/reuse-tool
    rev: v1.0.0
    hooks:
      - id: reuse
